FROM redis:6.2.6-bullseye

# RUN apt-get update
# RUN apt-get install -y libevent-dev

# COPY ./config/redis.conf /usr/local/etc/redis/redis.conf

# CMD ["redis-server", "/usr/local/etc/redis/redis.conf" ]
# COPY ./db /usr/local/etc/redis/db